### ISSUE TITLE
Test fails under Windows OS

### ISSUE THREAD

**Issue by Miklet** [kentcdodds/nps#129]
Hello, I wanted to start contributing to this project, but unfortunately tests are failing under Windows 8/10 and probably on any other Windows OS too.

- `nps` version: 5.0.5
- `node` version: 6.9.2
- `npm` version: 3.9.6

Scripts file (or at least the relevant bits):

```javascript
src\bin-utils\index.test.js
src\get-scripts-from-config.test.js
```

The command executed:

```console
npm start validate
```

The output:

```console
 ● loadConfig: logs and throws an error for a config that exports the wrong data type
[test]
[test]     expect(jest.fn()).toHaveBeenCalledWith(expected)
[test]
[test]     Expected mock function to have been called with:
[test]       [{"message": {"regexp": /C:\code\github\nps\src\bin-utils\fixtures\bad-data-type-config.js/}, "ref": "config-must-be-an-object"}]
[test]     But it was called with:
[test]       [{"message": "The package-scripts configuration (\"C:\\code\\github\\nps\\src\\bin-utils\\fixtures\\bad-data-type-config.js\") must be an object or a function that returns an object.", "ref": "config-must-be-an-object"}]
[test]
[test]       at Object.<anonymous> (src\bin-utils\index.test.js:65:21)
[test]
[test]   ● loadConfig: logs and throws an error for a config that exports a function that returns the wrong data type
[test]
[test]     expect(jest.fn()).toHaveBeenCalledWith(expected)
[test]
[test]     Expected mock function to have been called with:
[test]       [{"message": {"regexp": /C:\code\github\nps\src\bin-utils\fixtures\bad-function-data-type-config.js/}, "ref": "config-must-be-an-object"}]
[test]     But it was called with:
[test]       [{"message": "The package-scripts configuration (\"C:\\code\\github\\nps\\src\\bin-utils\\fixtures\\bad-function-data-type-config.js\") must be an object or a function that returns an object.", "ref": "config-must-be-an-object"}]
[test]
[test]       at Object.<anonymous> (src\bin-utils\index.test.js:90:21)
```
```
FAIL  cli-test\cli.test.js
[build.andValidate]   ● with config with default script
[build.andValidate]
[build.andValidate]     Error
[build.andValidate]       Error: expect(value).toMatchSnapshot()
[build.andValidate]
[build.andValidate]       Received value does not match stored snapshot 1.
[build.andValidate]
[build.andValidate]       - Snapshot
[build.andValidate]       + Received
[build.andValidate]
[build.andValidate]       @@ -1,6 +1,6 @@
[build.andValidate]        Object {
[build.andValidate]          "stderr": "",
[build.andValidate]          "stdout": "nps executing: echo "default script"
[build.andValidate]       -default script
[build.andValidate]       +"default script"
[build.andValidate]        ",
[build.andValidate]        }
[build.andValidate]       at cli-test\cli.test.js:23:36
[build.andValidate]
[build.andValidate]   ● with a missing config
[build.andValidate]
[build.andValidate]     expect(value).toMatchSnapshot()
[build.andValidate]
[build.andValidate]     Received value does not match stored snapshot 1.
[build.andValidate]
[build.andValidate]     - Snapshot
[build.andValidate]     + Received
[build.andValidate]
[build.andValidate]     @@ -1,5 +1,5 @@
[build.andValidate]      Object {
[build.andValidate]     -  "stderr": "Unable to find JS config at "./something-that-does-not-exist.js". Attempted to require as "<projectRootDir>/cli-test/fixtures/something-that-does-not-exist.js" https://github.com/kentcdodds/nps/blob/v0.0.0-semantically-released/other/ERRORS_AND_WARNINGS.md#unable-to-find-config
[build.andValidate]     +  "stderr": "Unable to find JS config at "./something-that-does-not-exist.js". Attempted to require as "<projectRootDir>\cli-test\fixtures\something-that-does-not-exist.js" https://github.com/kentcdodds/nps/blob/v0.0.0-semantically-released/other/ERRORS_AND_WARNINGS.md#unable-to-find-config
[build.andValidate]      ",
[build.andValidate]        "stdout": "",
[build.andValidate]      }
[build.andValidate]
[build.andValidate]       at cli-test\cli.test.js:23:36
[build.andValidate]       at process._tickCallback (internal\process\next_tick.js:103:7)
[build.andValidate]
[build.andValidate]   ● with --silent
[build.andValidate]
[build.andValidate]     Error
[build.andValidate]       Error: expect(value).toMatchSnapshot()
[build.andValidate]
[build.andValidate]       Received value does not match stored snapshot 1.
[build.andValidate]
[build.andValidate]       - Snapshot
[build.andValidate]       + Received
[build.andValidate]
[build.andValidate]       @@ -1,5 +1,5 @@
[build.andValidate]        Object {
[build.andValidate]          "stderr": "",
[build.andValidate]       -  "stdout": "test script
[build.andValidate]       +  "stdout": ""test script"
[build.andValidate]        ",
[build.andValidate]        }
[build.andValidate]       at cli-test\cli.test.js:23:36
[build.andValidate]       at process._tickCallback (internal\process\next_tick.js:103:7)
[build.andValidate]
[build.andValidate]   ● with --require
[build.andValidate]
[build.andValidate]     Error
[build.andValidate]       Error: expect(value).toMatchSnapshot()
[build.andValidate]
[build.andValidate]       Received value does not match stored snapshot 1.
[build.andValidate]
[build.andValidate]       - Snapshot
[build.andValidate]       + Received
[build.andValidate]
[build.andValidate]       @@ -1,6 +1,6 @@
[build.andValidate]        Object {
[build.andValidate]          "stderr": "",
[build.andValidate]          "stdout": "nps executing: echo "log"
[build.andValidate]       -log
[build.andValidate]       +"log"
[build.andValidate]        ",
[build.andValidate]        }
[build.andValidate]       at cli-test\cli.test.js:23:36
[build.andValidate]       at process._tickCallback (internal\process\next_tick.js:103:7)
```

Problem description:
It seems that tests are failing because of OS differences between Windows and Linux, especially paths.

Suggested solution:
Tests should be less OS dependent. Maybe use path.posix/path.win32.

**Comment by kentcdodds** [comment]
Ah, yeah, we should probably just fudge the output a little bit or something 🤔 Would you care to [makeapullrequest.com](http://makeapullrequest.com)?

**Comment by Miklet** [comment]
I can try to fix it :-)

**Comment by Miklet** [comment]
To test cli we use jest's snapshot technique which expects one, constant output. The output differentiates between OS platforms. There is no neutral output which is same on both. I guess we should standardize the output for Linux platform which is imo more natural i.e.:
`path/to/file` instead of `path\\to\\file`.

**Comment by kentcdodds** [comment]
I was thinking that we could just do the same kind of thing we do [here](https://github.com/kentcdodds/nps/blob/master/cli-test/cli.test.js#L33-L41) but instead swap `\\` for `/` or something..

**Comment by Miklet** [comment]
Yea, was thinking if we should play with actual output or only with output for tests. Will go with the one proposed by you.

**Comment by Miklet** [comment]
May I ask about access to repo? Wanted to make PR.

**Comment by kentcdodds** [comment]
Normally you make a fork and make a pull request from your fork. You may find the course referenced helpful: http://makeapullrequest.com

**Comment by Miklet** [comment]
I have found few more problems which I can fix, but I am surprised that those didn't appear when I was fixing cli tests. Also, I am surprised that this test doesn't fail on travis:
```
 FAIL  src\bin-utils\index.test.js
  ● loadConfig: logs and throws an error for a config that exports the wrong data type

    expect(jest.fn()).toHaveBeenCalledWith(expected)

    Expected mock function to have been called with:
      [{"message": {"regexp": /C:\code\github\nps\src\bin-utils\fixtures\bad-data-type-config.js/}, "ref": "config-must-be-an-object"}]
    But it was called with:
      [{"message": "The package-scripts configuration (\"C:\\code\\github\\nps\\src\\bin-utils\\fixtures\\bad-data-type-config.js\") must be an object or a function that returns an object.", "ref": "config-must-be-an-object"}]

      at Object.<anonymous> (src\bin-utils\index.test.js:65:21)
```
It's not about paths separators but content of message property is completely different.

**Comment by kentcdodds** [comment]
Ah, yeah! Thanks. I wonder if it would be helpful to write a [jest serializer](https://facebook.github.io/jest/docs/configuration.html#snapshotserializers-array-string) that will do this automatically for all snapshots 🤔 We could open source that and other people could use it to avoid problems like these in the future... Something to think about...

**Comment by kentcdodds** [comment]
Although this particular error would be kinda tricky because it's not a snapshot 😅 ignore me :)

**Comment by Miklet** [comment]
@kentcdodds Could you run `yarn start test` on your machine? Want to make sure it's reproducible and to see if it's correct that it's not failing on Travis.

**Comment by Miklet** [comment]
Oh nvm, I see it is problem with paths and just understood how `expect.stringMatching` function works. Will make another pr soon.

**Comment by Miklet** [comment]
Tests are working correctly now so I close my issue.

**Comment by kentcdodds** [comment]
Thanks to you! 😀
