### ISSUE TITLE
Unable to run `nps` without any arguments

### ISSUE THREAD

**Issue by nick-woodward** [kentcdodds/nps#170]
### Versions

- `nps` version: 5.7.1
- `node` version: 9.5.0
- `npm` version: 5.6.0

### Scripts file (or at least the relevant bits)

```yml
scripts:
  lint:
    script: eslint src/**/*.js tests/**/*.js
    description: Checks for any formatting errors
```

### The command executed

```console
$ nps
```

### The output

```console
~/Repositories/salte-auth/node_modules/nps/dist/bin-utils/parser.js:135
    var helpStyle = String(psConfig.options['help-style']);
                                           ^

TypeError: Cannot read property 'help-style' of undefined
    at showHelp (/Users/nick/Repositories/salte-auth/node_modules/nps/dist/bin-utils/parser.js:135:44)
    at parse (/Users/nick/Repositories/salte-auth/node_modules/nps/dist/bin-utils/parser.js:121:7)
    at Object.<anonymous> (/Users/nick/Repositories/salte-auth/node_modules/nps/dist/bin/nps.js:22:33)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
error Command failed with exit code 1.
```

### Problem description

The changes made in https://github.com/kentcdodds/nps/commit/9338d72cffb8efb7cf3951e6bf41ac92f11d95e5 have made it impossible to run `nps` without any arguments.

**The following will run without any problems:**

```sh
$ nps --config package-scripts.yml
```

**However the more natural:**

```sh
$ nps
```

Won't work, since the options object on psConfig will always be undefined for `yml` configs.

### Suggested solution

**Change:**

https://github.com/kentcdodds/nps/blob/b5769c9adad484c9ee8e4f23f95598075ebcbcae/src/bin-utils/index.js#L67-L72

**To:**

```js
function loadConfig(configPath, input) {
  let config;
  if (configPath.endsWith('.yml')) {
    config = loadYAMLConfig(configPath)
  } else {
    config = loadJSConfig(configPath)
  }

  // ...
```

**Comment by kentcdodds** [comment]
Makes total sense. I'd be happy to accept [a PR](http://makeapullrequest.com) for that :+1:
